// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Device struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Shortname string    `json:"shortname"`
	Enabled   bool      `json:"enabled"`
	Createdat time.Time `json:"createdat"`
	Updatedat time.Time `json:"updatedat"`
}

type Telemetry struct {
	ID        int64           `json:"id"`
	Deviceid  int64           `json:"deviceid"`
	Createdat time.Time       `json:"createdat"`
	Latitude  interface{}     `json:"latitude"`
	Longitude interface{}     `json:"longitude"`
	Value     sql.NullFloat64 `json:"value"`
	Value2    sql.NullFloat64 `json:"value2"`
	Value3    sql.NullFloat64 `json:"value3"`
	Value4    sql.NullFloat64 `json:"value4"`
}
