// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateTM(ctx context.Context, arg CreateTMParams) (Telemetry, error)
	DeleteDevice(ctx context.Context, id int64) error
	GetDevice(ctx context.Context, id int64) (Device, error)
	GetDevices(ctx context.Context, arg GetDevicesParams) ([]Device, error)
	GetTMByDeviceID(ctx context.Context, arg GetTMByDeviceIDParams) ([]Telemetry, error)
	GetTMByID(ctx context.Context, id int64) (Telemetry, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
}

var _ Querier = (*Queries)(nil)
